import { COLORS } from '@src/styles';
import { ACCOUNT_CONSTANT } from 'incognito-chain-web-js/build/wallet';

export const TX_STATUS_COLOR = {
  [ACCOUNT_CONSTANT.TX_STATUS.PROCESSING]: COLORS.colorGreyBold,
  [ACCOUNT_CONSTANT.TX_STATUS.TXSTATUS_UNKNOWN]: COLORS.orange,
  [ACCOUNT_CONSTANT.TX_STATUS.TXSTATUS_FAILED]: COLORS.red,
  [ACCOUNT_CONSTANT.TX_STATUS.TXSTATUS_PENDING]: COLORS.colorBlue,
  [ACCOUNT_CONSTANT.TX_STATUS.TXSTATUS_SUCCESS]: COLORS.green,
};
